### ISSUE TITLE
Slugs for URLs

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1750]
# Task
Add URL slug capabilities to Apinf. URL slugs will be used for organization URL paths, and possibly for APIs.

# Original request
When an API is created, the URL generated is one that includes a random string. It would be nice to have slugs instead.
This way, a URL can more easily be shared.

# Definition of done
- [x] URL slug package has been chosen and installed
- [x] Organization schema contains `slug` field
  - [ ] Organization slug values are unique
- [ ] Single organization route uses url slug as unique identifier 

# Resources
https://github.com/todda00/meteor-friendly-slugs
http://stackoverflow.com/questions/32575086/pretty-urls-with-iron-router-and-friendly-slug-package

**Comment by bajiat** [comment]
This should be done together with Organization Management, because Organization Management causes backwards incompatible changes to routing - as does this change. So the proposal is to do both changes at the same time. Hence, I've labeled the issue with Organization Management.

**Comment by philippeluickx** [comment]
We'd have to consider adding a username to the URL as well instead of an organization. This way we can then have apinf.io/philippe/maps API and apinf.io/taija/maps

**Comment by jykae** [comment]
interested

**Comment by nnn** [comment]
I am going with https://github.com/todda00/meteor-friendly-slugs
@apinf/developers if you guys have any other suggestions, please, let me know.
