### ISSUE TITLE
Setup a separate API Umbrella instance for testing multiproxy

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1873]
Deploy one API Umbrella instance on a web-accessible VM. This can be used for testing the multiproxy implementation.

* [x] API Umbrella has been deployed on a new VM.
  *Note: this is a standalone VM without any Apinf instance*
* [x] The VM has proper certificate, e.g. LetsEncrypt
* [x] The server has a DNS record

**Comment by bajiat** [comment]
@shaliko Can you deploy Api Umbrella?

**Comment by shaliko** [comment]
@bajiat Sure, some specific server or deploy it to DigitalOcean?

**Comment by bajiat** [comment]
Deployment finished. Closing the issue.
