### ISSUE TITLE
Try to simplify the username regular expression, if possible

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1985]
# Context
Pull request #1574 made changes to the username regular expression.

## Before
```js
// Username must be 3-15 alphanumeric string with hyphens allowed.
const UsernameRegEx = /^[a-z0-9A-Z_\-]{3,15}$/;
```

## After
```js
// Username must be 3-15 alphanumeric string with hyphens allowed.
const UsernameRegEx = /^(?!\d)(?!.*-.*-)(?!.*-$)(?!-)[a-zA-Z0-9-]{3,15}$/;
```

> ^ - Match at the beginning
(?!\d) - Do not match if the string starts with a digit
(?!.\*-.\*-) - Do not match if the string has 2 hyphens anywhere
(?!.\*-$) - Do not match if the string ends with a hyphen
(?!-) - Do not match if the string starts with a hyphen
[a-zA-Z0-9-_]{3,15} - Match 3 to 15 characters from the range specified (username can have 1 hyphen and under_score with chars and numbers in it)
$ - Assert the end of string.
# Issue
We have recently modified the reqular expression, and had trouble understanding its purpose. The comment does not describe the regular expression.

# Task
- [ ] Determine how the regular expression works as currently written. 
- [ ] Add comments describing why the regular expression is written as it is. 
- [ ] If possible, simplify the regular expression.

**Comment by brylie** [comment]
@nnn & @jykae, why did we change the username RegEx in pull request #1574? What does the current regex do, in plain language?

/cc @bajiat

**Comment by brylie** [comment]
It seems like the regular expression was designed to match the rules of Github usernames:

![screenshot_20161221_135614](https://cloud.githubusercontent.com/assets/17307/21388537/5d6604da-c785-11e6-9ca4-3b0ecfcb712b.png)

Since we are not syncing usernames upstream **to** Github, I am not sure that we need as strict of username rules.

**Comment by brylie** [comment]
Also, Github usernames can start with numbers, so we don't need to prevent our usernames from starting with numbers, in any case:

```js
// We can probably remove this from our regex
const usernameRegex = /^(?!\d) ........
```

**Comment by brylie** [comment]
Also, Github usernames can have multiple hyphens, just not together. So, the following can be removed or modified:

```js
.....(?!.*-.*-).....
```
