### ISSUE TITLE
Research options for proper API Umbrella API backend prefix and analytics handling

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2115]
Related to issues #2090, #2093, #2032 

At the moment, Apinf UI allows user to use any proxy backend path as long as it is unique. However, API Umbrella matches APIs for calls by the matching order field. As a result, calls maybe terminating in a way user is not expecting.As a worst case scenario, they ends up calling a completely different API.

API Umbrella Analytics provides us with a drill-down analytics endpoint. However, the date returned is fit to be used in API Umbrella drill-down dashboard. Since our dashboard differs dramatically from the API Umbrella dashboard, we need access to the raw or aggregated ElasticSearch data. 

Additionally, we need a way link to the analytics data to particular API ID. This allows us to delete the API along with corresponding analytics data. This would also improve our API owner dashboard.

Lastly, we are interested to have analytics about the API key usage per API. API key is available in the API Umbrella drilldown dashboard, but does not appear to be available in the drilldown analytics results.

# Definition of done
* [x] Options for solving the 4 interrelated problems documented in our documentation repository.
* [x] Pros and cons for each approach.
* [ ] As needed, open issues in API Umbrella backlog to get the discussion started.

**Comment by bajiat** [comment]
@shaliko @marla-singer Please estimate this research task.

**Comment by marla-singer** [comment]
@bajiat 
We think that it should be easy to start from these issues #2032 and #2093. The main idea is to add the unique namespaces. This solution will help to resolve both issues: 
    - A user will not be able to call other APIs.
    - A user will be able to delete all ElasticSearch data associated with his API including the nested requests.

1. #2093 Check that the case is or not reproduced when we have the APIs with frontend prefixes as `/maps/` and `/google/maps/` and try to create a condition for uniqueness. The estimate is 2-4 days. It depends on checking above

1. #2032 After adding the namespaces make sure that user can delete just owned analytics data including the nested requested. The estimate is 2 days

2. #2090 In this issue we need to learn can we use the current REST API to get analytics data or should we create another endpoint for that. The estimate is 4 days

**Totally estimate is 8-12 days**

**Comment by bajiat** [comment]
@marla-singer @shaliko Can I ask for one clarification: Is the estimate - 8 days -for the documented research with options?

**Comment by marla-singer** [comment]
@bajiat Yes. This estimate includes time for the documented as well.

**Comment by marla-singer** [comment]
@bajiat Uploaded the research paper

> At the moment, Apinf UI allows user to use any proxy backend path as long as it is unique. However, API Umbrella matches APIs for calls by the matching order field. As a result, calls maybe terminating in a way user is not expecting.As a worst case scenario, they ends up calling a completely different API.
> Additionally, we need a way link to the analytics data to particular API ID. This allows us to delete the API along with corresponding analytics data. This would also improve our API owner dashboard.

This problems are grouped together. [Link to the research document](https://github.com/apinf/docs/blob/master/docs/research/Namespace%20for%20frontend-prefix.md)

> API Umbrella Analytics provides us with a drill-down analytics endpoint. However, the date returned is fit to be used in API Umbrella drill-down dashboard. Since our dashboard differs dramatically from the API Umbrella dashboard, we need access to the raw or aggregated ElasticSearch data.

[Link to the research document](https://github.com/apinf/docs/blob/master/docs/research/Drill-down%20analytics%20endpoint.md)

> Lastly, we are interested to have analytics about the API key usage per API. API key is available in the API Umbrella drilldown dashboard, but does not appear to be available in the drilldown analytics results.

[Link to the research document](https://github.com/apinf/docs/blob/master/docs/research/API%20key%20per%20API.md)

**Comment by brylie** [comment]
Notes on **Namespace for frontend-prefix** document.

# The first option
- we need to support both **username** and **organization** namespacing
- this doesn't *completely* solve the **matching order** issue
  - e.g. user *brylie* creates `/brylie/alternative` and `/brylie/alternative/rock/seattle/nirvana`
  - matching might still resolve `/brylie/alternative/rock/seattle/nirvana` to `/brylie/alternative` backend

**Comment by marla-singer** [comment]
@brylie Can't understand what the problem is. Could you please describe more detail?

**Comment by brylie** [comment]
@marla-singer please refer to discussion in your [original issue](https://github.com/apinf/platform/issues/2093). What specifically should we clarify?

**Comment by brylie** [comment]
Here is a screenshot of the API Umbrella API Backends list, showing the **matching order** field:

![API Umbrella Backend matching order](https://cloud.githubusercontent.com/assets/17307/22823321/bc960bf2-ef8b-11e6-8f98-6081cfafaad9.png)

**Comment by bajiat** [comment]
@marla-singer We are commenting this together with @brylie. Not sure what to answer "what the problem is" since we don't know which comments you are referring to

**Comment by marla-singer** [comment]
> Notes on Namespace for frontend-prefix document.

@bajiat I told about this sentence. Is it just note for clarification or note as a remark for me?

**Comment by bajiat** [comment]
> Notes on Namespace for frontend-prefix document.

We are commenting document by document and wanted to indicate which document we are commenting.

**Comment by brylie** [comment]
Notes on [Drill-down analytics endpoint](https://github.com/apinf/docs/blob/master/docs/research/Drill-down%20analytics%20endpoint.md) document.

## How to get data

### Direct request to ElasticSearch

Cons
2. our current **multi-proxy** setup allows the Proxy to be deployed on any server, accessible via public Internet
  - our current deployments usually have API Umbrella and Apinf on the same VM, but we want to allow organizations to manage their own Proxy instance outside of our server

**Comment by brylie** [comment]
Notes on [API key per API](https://github.com/apinf/docs/blob/master/docs/research/API%20key%20per%20API.md) document.

**Comment by marla-singer** [comment]
> Is your impression that we can get analytics per API key
- through ElasticSearch?
- through Admin API?

I didn't consider ElasticSearch way in Research. But as the first step of Admin API familiarization, we can get analytics per API key through Admin API
