### ISSUE TITLE
Test Umbrella version 0.14.0

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2389]
# Goal

Smoke-testing for API Umbrella 0.14.0: go through the key proxy use cases with a new release of API Umbrella.

# Environment

nightly.apinf.io 
Proxy: API Umbrella 0.14.0

# Definition of done
* [x] Add a new API and connect it to the API Umbrella 0.14.0 proxy
* [x] Get API key for the new proxy
* [x] Make calls to the new API
* [x] Check analytics

Optionally, you can also test
* Disabling requirement for API key (make calls to test this)
* Rate limiting settings

**Comment by saralavanip** [comment]
Reported issues: #2424, # 2425, #2436,#2450
