### ISSUE TITLE
Audit and clean up project dependencies

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2911]
As our project has grown, we have added many dependencies. At times, we may have changed features, so they no longer rely on previous dependencies. In these cases, we should also have removed the dependencies, but it is not a certainty.

# Goal
* Improve the user experience, because the unnecessary dependencies makes loading take longer.
*  Improve our understanding of what dependencies are active or inactive in our project. 
* Reduce the build size (5 MB( by removing unused dependencies.

# Task
- [x] Get list(s) of project dependencies
    - [x] Atmosphere packages
    - [ ] NPM packages
- [ ] Determine which dependencies are no longer in use, or have minimal use
- [ ] Remove unused packages
    - [ ] Replace minimally used packages with custom code, where possible
- [ ] Determine which Atmosphere packages have NPM equivalents
- [ ] Try to replace Atmosphere packages with NPM packages, where possible

# Atmosphere package audit
As of Meteor 1.5.2, we can easily see our dependency tree:

```
# meteor list --tree

accounts-base@1.3.2                           
├─┬ callback-hook@1.0.10                      
│ └── underscore@1.0.10                       
├── check@1.2.5 (top level)                   
├─┬ ddp@1.3.0                                 
│ ├─┬ ddp-client@2.1.0                        
│ │ ├── check@1.2.5 (top level)               
│ │ ├─┬ ddp-common@1.2.9                      
│ │ │ ├── check@1.2.5 (top level)             
│ │ │ ├── ejson@1.0.14 (top level)            
│ │ │ ├── random@1.0.10 (top level)           
│ │ │ ├─┬ retry@1.0.9                         
│ │ │ │ ├── random@1.0.10 (top level)         
│ │ │ │ └── underscore@1.0.10                 
│ │ │ ├── tracker@1.1.3                       
│ │ │ └── underscore@1.0.10                   
│ │ ├─┬ diff-sequence@1.0.7                   
│ │ │ ├── ejson@1.0.14 (top level)            
│ │ │ └── underscore@1.0.10                   
│ │ ├── ecmascript@0.8.2 (top level)          
│ │ ├── ejson@1.0.14 (top level)              
│ │ ├─┬ id-map@1.0.9                          
│ │ │ ├── ejson@1.0.14 (top level)            
│ │ │ └── underscore@1.0.10                   
│ │ ├─┬ mongo-id@1.0.6                        
│ │ │ ├── ejson@1.0.14 (top level)            
│ │ │ ├── id-map@1.0.9 (expanded above)       
│ │ │ └── random@1.0.10 (top level)           
│ │ ├── random@1.0.10 (top level)             
│ │ ├── retry@1.0.9 (expanded above)          
│ │ ├── tracker@1.1.3                         
│ │ └── underscore@1.0.10                     
│ └─┬ ddp-server@2.0.0                        
│   ├── callback-hook@1.0.10 (expanded above) 
│   ├── check@1.2.5 (top level)               
│   ├── ddp-client@2.1.0 (expanded above)     
│   ├── ddp-common@1.2.9 (expanded above)     
│   ├── diff-sequence@1.0.7 (expanded above)                                                                                                                                                                                                                                   
│   ├── ecmascript@0.8.2 (top level)                                                                                                                                                                                                                                           
│   ├── ejson@1.0.14 (top level)                                                                                                                                                                                                                                               
│   ├─┬ minimongo@1.3.0                                                                                                                                                                                                                                                        
│   │ ├── diff-sequence@1.0.7 (expanded above)                                                                                                                                                                                                                                 
│   │ ├── ecmascript@0.8.2 (top level)                                                                                                                                                                                                                                         
│   │ ├── ejson@1.0.14 (top level)                                                                                                                                                                                                                                             
│   │ ├─┬ geojson-utils@1.0.10                                                                                                                                                                                                                                                 
│   │ │ └─┬ modules@0.10.0                                                                                                                                                                                                                                                     
│   │ │   └── modules-runtime@0.8.0                                                                                                                                                                                                                                            
│   │ ├── id-map@1.0.9 (expanded above)                                                                                                                                                                                                                                        
│   │ ├── mongo-id@1.0.6 (expanded above)                                                                                                                                                                                                                                      
│   │ ├─┬ ordered-dict@1.0.9                                                                                                                                                                                                                                                   
│   │ │ └── underscore@1.0.10                                                                                                                                                                                                                                                  
│   │ ├── random@1.0.10 (top level)                                                                                                                                                                                                                                            
│   │ └── tracker@1.1.3                                                                                                                                                                                                                                                        
│   ├── mongo-id@1.0.6 (expanded above)                                                                                                                                                                                                                                        
│   ├── random@1.0.10 (top level)                                                                                                                                                                                                                                              
│   ├── retry@1.0.9 (expanded above)                                                                                                                                                                                                                                           
│   ├─┬ routepolicy@1.0.12                                                                                                                                                                                                                                                     
│   │ ├── underscore@1.0.10                                                                                                                                                                                                                                                    
│   │ └─┬ webapp@1.3.18                                                                                                                                                                                                                                                        
│   │   ├─┬ boilerplate-generator@1.2.0                                                                                                                                                                                                                                        
│   │   │ ├── ecmascript@0.8.2 (top level)                                                                                                                                                                                                                                     
│   │   │ └── underscore@1.0.10                                                                                                                                                                                                                                                
│   │   ├── ecmascript@0.8.2 (top level)                                                                                                                                                                                                                                       
│   │   ├── logging@1.1.17 (top level)                                                                                                                                                                                                                                         
│   │   ├── routepolicy@1.0.12 (expanded above)                                                                                                                                                                                                                                
│   │   ├── underscore@1.0.10                 
│   │   └─┬ webapp-hashing@1.0.9              
│   │     ├── ecmascript@0.8.2 (top level)    
│   │     └── underscore@1.0.10               
│   ├── underscore@1.0.10                     
│   └── webapp@1.3.18 (expanded above)        
├─┬ ddp-rate-limiter@1.0.7                    
│ └─┬ rate-limit@1.0.8                        
│   ├── random@1.0.10 (top level)             
│   └── underscore@1.0.10                     
├── ecmascript@0.8.2 (top level)              
├── ejson@1.0.14 (top level)                  
├─┬ localstorage@1.1.1                        
│ └── random@1.0.10 (top level)               
├── mongo@1.2.0 (top level)                   
├── random@1.0.10 (top level)                 
├── reactive-var@1.0.11 (top level)           
├── service-configuration@1.0.11 (top level)  
├── tracker@1.1.3                             
└── underscore@1.0.10                         
accounts-github@1.3.0                         
├── accounts-base@1.3.2 (top level)           
├─┬ accounts-oauth@1.1.15                     
│ ├── accounts-base@1.3.2 (top level)         
│ ├── check@1.2.5 (top level)                 
│ ├─┬ oauth@1.1.13                            
│ │ ├── base64@1.0.10                         
│ │ ├── check@1.2.5 (top level)               
│ │ ├── localstorage@1.1.1 (expanded above)   
│ │ ├── logging@1.1.17 (top level)            
│ │ ├── mongo@1.2.0 (top level)               
│ │ ├── reload@1.1.11 (top level)             
│ │ ├── routepolicy@1.0.12 (expanded above)   
│ │ ├── service-configuration@1.0.11 (top level)
│ │ ├── underscore@1.0.10                     
│ │ ├─┬ url@1.1.0                             
│ │ │ └── underscore@1.0.10                   
│ │ └── webapp@1.3.18 (expanded above)        
│ ├── random@1.0.10 (top level)               
│ ├── underscore@1.0.10                       
│ └── webapp@1.3.18 (expanded above)          
└─┬ github-oauth@1.2.0                        
  ├── http@1.2.12 (top level)                 
  ├── oauth@1.1.13 (expanded above)           
  ├─┬ oauth2@1.1.11                           
  │ ├── oauth@1.1.13 (expanded above)         
  │ ├── random@1.0.10 (top level)             
  │ └── service-configuration@1.0.11 (top level)
  ├── random@1.0.10 (top level)               
  ├── service-configuration@1.0.11 (top level)
  └── underscore@1.0.10                       
accounts-password@1.4.0                       
├── accounts-base@1.3.2 (top level)           
├── check@1.2.5 (top level)                   
├── ddp@1.3.0 (expanded above)                
├── ecmascript@0.8.2 (top level)              
├── ejson@1.0.14 (top level)                  
├── email@1.2.3                               
├─┬ npm-bcrypt@0.9.3                          
│ └── modules@0.10.0 (expanded above)         
├── random@1.0.10 (top level)                 
├── sha@1.0.9                                 
├─┬ srp@1.0.10                                
│ ├── check@1.2.5 (top level)                 
│ ├── random@1.0.10 (top level)               
│ ├── sha@1.0.9                               
│ └── underscore@1.0.10                       
└── underscore@1.0.10                         
accounts-ui@1.1.9                             
├── accounts-base@1.3.2 (top level)           
├─┬ accounts-ui-unstyled@1.2.1                
│ ├── accounts-base@1.3.2 (top level)         
│ ├── jquery@1.11.10 (top level)              
│ ├── less@2.7.9 (top level)                  
│ ├── service-configuration@1.0.11 (top level)
│ ├── session@1.1.7 (top level)               
│ ├─┬ templating@1.3.2                        
│ │ ├─┬ templating-compiler@1.3.2             
│ │ │ ├─┬ caching-html-compiler@1.1.2         
│ │ │ │ ├─┬ caching-compiler@1.1.9            
│ │ │ │ │ ├── ecmascript@0.8.2 (top level)    
│ │ │ │ │ └── random@1.0.10 (top level)       
│ │ │ │ ├── ecmascript@0.8.2 (top level)      
│ │ │ │ ├─┬ templating-tools@1.1.2            
│ │ │ │ │ ├── ecmascript@0.8.2 (top level)    
│ │ │ │ │ ├─┬ spacebars-compiler@1.1.3        
│ │ │ │ │ │ ├─┬ blaze-tools@1.0.10            
│ │ │ │ │ │ │ ├─┬ htmljs@1.0.11               
│ │ │ │ │ │ │ │ └─┬ deps@1.0.12               
│ │ │ │ │ │ │ │   └── tracker@1.1.3           
│ │ │ │ │ │ │ └── underscore@1.0.10           
│ │ │ │ │ │ ├─┬ html-tools@1.0.11             
│ │ │ │ │ │ │ └── htmljs@1.0.11 (expanded above)
│ │ │ │ │ │ ├── htmljs@1.0.11 (expanded above)
│ │ │ │ │ │ └── underscore@1.0.10             
│ │ │ │ │ └── underscore@1.0.10               
│ │ │ │ └── underscore@1.0.10                 
│ │ │ ├── ecmascript@0.8.2 (top level)        
│ │ │ └── templating-tools@1.1.2 (expanded above)
│ │ └─┬ templating-runtime@1.3.2              
│ │   ├─┬ blaze@2.3.2                         
│ │   │ ├── check@1.2.5 (top level)           
│ │   │ ├── htmljs@1.0.11 (expanded above)    
│ │   │ ├── jquery@1.11.10 (top level)        
│ │   │ ├─┬ observe-sequence@1.0.16           
│ │   │ │ ├── diff-sequence@1.0.7 (expanded above)
│ │   │ │ ├── mongo-id@1.0.6 (expanded above) 
│ │   │ │ ├── random@1.0.10 (top level)       
│ │   │ │ ├── tracker@1.1.3                   
│ │   │ │ └── underscore@1.0.10               
│ │   │ ├── ordered-dict@1.0.9 (expanded above)
│ │   │ ├── reactive-var@1.0.11 (top level)   
│ │   │ ├── tracker@1.1.3                     
│ │   │ └── underscore@1.0.10                 
│ │   ├── spacebars@1.0.15 (top level)        
│ │   ├── templating-compiler@1.3.2 (expanded above)
│ │   └── underscore@1.0.10                   
│ ├── tracker@1.1.3                           
│ └── underscore@1.0.10                       
└── less@2.7.9 (top level)                    
alanning:roles@1.2.16                         
├── accounts-base@1.3.2 (top level)           
├── check@1.2.5 (top level)                   
├── mongo@1.2.0 (top level)                   
├── tracker@1.1.3                             
└── underscore@1.0.10                         
aldeed:autoform@5.8.1                         
├── aldeed:simple-schema@1.5.3 (top level)    
├── blaze@2.3.2 (expanded above)              
├── check@1.2.5 (top level)                   
├── deps@1.0.12 (expanded above)              
├── ejson@1.0.14 (top level)                  
├── jquery@1.11.10 (top level)                
├─┬ livedata@1.0.18                           
│ └── ddp@1.3.0 (expanded above)              
├── momentjs:moment@2.18.1                    
├── random@1.0.10 (top level)                 
├── reactive-dict@1.1.9 (top level)           
├── reactive-var@1.0.11 (top level)           
├── templating@1.3.2 (expanded above)         
├─┬ ui@1.0.13                                 
│ └── blaze@2.3.2 (expanded above)            
└── underscore@1.0.10                         
aldeed:autoform-bs-button-group-input@1.0.3   
├── aldeed:autoform@5.8.1 (top level)         
├── blaze@2.3.2 (expanded above)              
└── templating@1.3.2 (expanded above)         
aldeed:collection2@2.10.0                     
├─┬ aldeed:collection2-core@1.2.0             
│ ├── aldeed:simple-schema@1.5.3 (top level)  
│ ├── check@1.2.5 (top level)                 
│ ├── ejson@1.0.14 (top level)                
│ ├── minimongo@1.3.0 (expanded above)        
│ ├── mongo@1.2.0 (top level)                 
│ ├─┬ raix:eventemitter@0.1.3                 
│ │ └── underscore@1.0.10                     
│ └── underscore@1.0.10                       
├─┬ aldeed:schema-deny@1.1.0                  
│ ├── aldeed:collection2-core@1.2.0 (expanded above)
│ ├── check@1.2.5 (top level)                 
│ ├── minimongo@1.3.0 (expanded above)        
│ └── underscore@1.0.10                       
└─┬ aldeed:schema-index@1.1.1                 
  ├── aldeed:collection2-core@1.2.0 (expanded above)
  ├── check@1.2.5 (top level)                 
  ├── ecmascript@0.8.2 (top level)            
  ├── minimongo@1.3.0 (expanded above)        
  └── underscore@1.0.10                       
aldeed:simple-schema@1.5.3                    
├── check@1.2.5 (top level)                   
├── deps@1.0.12 (expanded above)              
├─┬ mdg:validation-error@0.5.1                
│ ├── check@1.2.5 (top level)                 
│ └── ecmascript@0.8.2 (top level)            
├── random@1.0.10 (top level)                 
└── underscore@1.0.10                         
aldeed:template-extension@4.1.0               
├── blaze@2.3.2 (expanded above)              
├── ecmascript@0.8.2 (top level)              
├── templating@1.3.2 (expanded above)         
└── tracker@1.1.3                             
apinf:accounts-admin-ui@0.3.2                 
├── accounts-password@1.4.0 (top level)       
├── accounts-ui@1.1.9 (top level)             
├── alanning:roles@1.2.16 (top level)         
├─┬ apinf:first-admin@0.1.2                   
│ ├── accounts-base@1.3.2 (top level)         
│ └─┬ apinf:create-role-if-undefined@0.1.1    
│   └── alanning:roles@1.2.16 (top level)     
├── kurounin:pagination-blaze@1.0.2 (top level)
├── session@1.1.7 (top level)                 
├── templating@1.3.2 (expanded above)         
├── twbs:bootstrap@3.3.6 (top level)          
└── underscore@1.0.10                         
apinf:api-umbrella@1.4.1                      
├── http@1.2.12 (top level)                   
└── underscore@1.0.10                         
apinf:autoform-bs-datepicker@1.1.2            
├── aldeed:autoform@5.8.1 (top level)         
├── blaze@2.3.2 (expanded above)              
└── templating@1.3.2 (expanded above)         
apinf:restivus-swagger@0.4.0                  
├── ecmascript@0.8.2 (top level)              
├── nimble:restivus@0.8.11 (top level)        
└── underscore@1.0.10                         
aramk:quill@0.1.1                             
├─┬ coffeescript@1.12.7_1                     
│ ├─┬ babel-runtime@1.0.1                     
│ │ ├── modules@0.10.0 (expanded above)       
│ │ └─┬ promise@0.9.0                         
│ │   └── modules@0.10.0 (expanded above)     
│ ├── caching-compiler@1.1.9 (expanded above) 
│ ├─┬ coffeescript-compiler@1.12.7_1          
│ │ ├─┬ babel-compiler@6.20.0                 
│ │ │ └─┬ ecmascript-runtime@0.4.1            
│ │ │   ├─┬ ecmascript-runtime-client@0.4.3   
│ │ │   │ ├── modules@0.10.0 (expanded above) 
│ │ │   │ └── promise@0.9.0 (expanded above)  
│ │ │   └─┬ ecmascript-runtime-server@0.4.1   
│ │ │     ├── modules@0.10.0 (expanded above) 
│ │ │     └── promise@0.9.0 (expanded above)  
│ │ └── ecmascript@0.8.2 (top level)          
│ ├── ecmascript@0.8.2 (top level)            
│ ├── ecmascript-runtime@0.4.1 (expanded above)
│ └── promise@0.9.0 (expanded above)          
├── jquery@1.11.10 (top level)                
├── less@2.7.9 (top level)                    
├── templating@1.3.2 (expanded above)         
├── trever:quill@0.0.5                        
└── underscore@1.0.10                         
arillo:flow-router-helpers@0.5.2              
├── check@1.2.5 (top level)                   
├── coffeescript@1.12.7_1 (expanded above)    
├── templating@1.3.2 (expanded above)         
├── underscore@1.0.10                         
└── zimme:active-route@2.3.2 (top level)      
benmgreene:moment-range@2.10.6                
└── momentjs:moment@2.18.1                    
blaze-html-templates@1.1.2                    
├── blaze@2.3.2 (expanded above)              
├── spacebars@1.0.15 (top level)              
├── templating@1.3.2 (expanded above)         
└── ui@1.0.13 (expanded above)                
cfs:filesystem@0.1.2                          
├─┬ cfs:base-package@0.0.30                   
│ ├── deps@1.0.12 (expanded above)            
│ ├── ejson@1.0.14 (top level)                
│ └── underscore@1.0.10                       
└─┬ cfs:storage-adapter@0.2.3                 
  ├── cfs:base-package@0.0.30 (expanded above)
  ├── check@1.2.5 (top level)                 
  ├── deps@1.0.12 (expanded above)            
  ├── ejson@1.0.14 (top level)                
  ├── livedata@1.0.18 (expanded above)        
  ├─┬ mongo-livedata@1.0.12                   
  │ └── mongo@1.2.0 (top level)               
  └── raix:eventemitter@0.1.3 (expanded above)
check@1.2.5                                   
├── ejson@1.0.14 (top level)                  
├── modules@0.10.0 (expanded above)           
└── underscore@1.0.10                         
dandv:jquery-rateit@1.0.22_2                  
└── jquery@1.11.10 (top level)                
dburles:collection-helpers@1.1.0              
├── mongo@1.2.0 (top level)                   
└── underscore@1.0.10                         
deepwell:bootstrap-datepicker2@1.3.0          
└── jquery@1.11.10 (top level)                
dynamic-import@0.1.1                          
├── check@1.2.5 (top level)                   
├── ddp@1.3.0 (expanded above)                
├── ecmascript@0.8.2 (top level)              
├── modules@0.10.0 (expanded above)           
└── promise@0.9.0 (expanded above)            
ecmascript@0.8.2                              
├── babel-compiler@6.20.0 (expanded above)    
├── babel-runtime@1.0.1 (expanded above)      
├── ecmascript-runtime@0.4.1 (expanded above) 
├── modules@0.10.0 (expanded above)           
└── promise@0.9.0 (expanded above)            
ejson@1.0.14                                  
├── base64@1.0.10                             
└── ecmascript@0.8.2 (top level)              
email@1.2.3                                   
fastclick@1.0.13                              
fortawesome:fontawesome@4.7.0                 
froatsnook:valid-email@1.0.0                  
└── check@1.2.5 (top level)                   
github-config-ui@1.0.0                        
└── templating@1.3.2 (expanded above)         
gwendall:autoform-i18n@0.1.9_1                
├── aldeed:simple-schema@1.5.3 (top level)    
├── tap:i18n@1.8.2 (top level)                
├── templating@1.3.2 (expanded above)         
└── underscore@1.0.10                         
harrison:papa-parse@1.1.7                     
└── jquery@1.11.10 (top level)                
http@1.2.12                                   
├── ecmascript@0.8.2 (top level)              
├── underscore@1.0.10                         
└── url@1.1.0 (expanded above)                
jquery@1.11.10                                
└── modules@0.10.0 (expanded above)           
juliancwirko:s-alert@3.2.0                    
├── jquery@1.11.10 (top level)                
├── mongo@1.2.0 (top level)                   
├── session@1.1.7 (top level)                 
├── templating@1.3.2 (expanded above)         
├── ui@1.0.13 (expanded above)                
└── underscore@1.0.10                         
juliancwirko:s-alert-stackslide@3.1.3         
└── juliancwirko:s-alert@3.2.0 (top level)    
kadira:blaze-layout@2.3.0                     
├── blaze@2.3.2 (expanded above)              
├── jquery@1.11.10 (top level)                
├── reactive-dict@1.1.9 (top level)           
├── templating@1.3.2 (expanded above)         
├── tracker@1.1.3                             
└── underscore@1.0.10                         
kadira:dochead@1.5.0                          
├── ecmascript@0.8.2 (top level)              
├─┬ es5-shim@4.6.15                           
│ └── modules@0.10.0 (expanded above)         
└── tracker@1.1.3                             
kadira:flow-router@2.12.1                     
├── ejson@1.0.14 (top level)                  
├── modules@0.10.0 (expanded above)           
├── reactive-dict@1.1.9 (top level)           
├── reactive-var@1.0.11 (top level)           
├── tracker@1.1.3                             
└── underscore@1.0.10                         
kurounin:pagination@1.0.21                    
├── check@1.2.5 (top level)                   
├── ecmascript@0.8.2 (top level)              
├── meteor-base@1.1.0 (top level)             
├── mongo@1.2.0 (top level)                   
├── reactive-dict@1.1.9 (top level)           
├── reactive-var@1.0.11 (top level)           
├── tmeasday:publish-counts@0.8.0 (top level) 
├── tracker@1.1.3                             
└── underscore@1.0.10                         
kurounin:pagination-blaze@1.0.2               
├── blaze@2.3.2 (expanded above)              
├── kurounin:pagination@1.0.21 (top level)    
├── meteor-base@1.1.0 (top level)             
├── reactive-dict@1.1.9 (top level)           
├── reactive-var@1.0.11 (top level)           
├── templating@1.3.2 (expanded above)         
└── underscore@1.0.10                         
less@2.7.9                                    
├── caching-compiler@1.1.9 (expanded above)   
├── ecmascript@0.8.2 (top level)              
└── underscore@1.0.10                         
logging@1.1.17                                
├── ejson@1.0.14 (top level)                  
├── modules@0.10.0 (expanded above)           
└── underscore@1.0.10                         
matb33:collection-hooks@0.8.4                 
├── ejson@1.0.14 (top level)                  
├── minimongo@1.3.0 (expanded above)          
├── mongo@1.2.0 (top level)                   
├── tracker@1.1.3                             
└── underscore@1.0.10                         
meteor-base@1.1.0                             
├── ddp@1.3.0 (expanded above)                
├── dynamic-import@0.1.1 (top level)          
├─┬ hot-code-push@1.0.4                       
│ ├─┬ autoupdate@1.3.12                       
│ │ ├── check@1.2.5 (top level)               
│ │ ├── ddp@1.3.0 (expanded above)            
│ │ ├── http@1.2.12 (top level)               
│ │ ├── mongo@1.2.0 (top level)               
│ │ ├── random@1.0.10 (top level)             
│ │ ├── retry@1.0.9 (expanded above)          
│ │ ├── tracker@1.1.3                         
│ │ ├── underscore@1.0.10                     
│ │ └── webapp@1.3.18 (expanded above)        
│ └── reload@1.1.11 (top level)               
├── livedata@1.0.18 (expanded above)          
├── underscore@1.0.10                         
└── webapp@1.3.18 (expanded above)            
meteorhacks:subs-manager@1.6.4                
├── deps@1.0.12 (expanded above)              
├── ejson@1.0.14 (top level)                  
└── underscore@1.0.10                         
michalvalasek:autoform-bootstrap-colorpicker@0.1.0
├── aldeed:autoform@5.8.1 (top level)         
└── templating@1.3.2 (expanded above)         
mizzao:sharejs@0.9.0                          
├── ecmascript@0.8.2 (top level)              
├── handlebars@1.0.7                          
├── modules@0.10.0 (expanded above)           
├── mongo-livedata@1.0.12 (expanded above)    
├── routepolicy@1.0.12 (expanded above)       
├── templating@1.3.2 (expanded above)         
├── underscore@1.0.10                         
└── webapp@1.3.18 (expanded above)            
mizzao:sharejs-ace@1.4.1                      
├── ecmascript@0.8.2 (top level)              
├── mizzao:sharejs@0.9.0 (top level)          
├── modules@0.10.0 (expanded above)           
└── templating@1.3.2 (expanded above)         
mobile-experience@1.0.4                       
├── fastclick@1.0.13                          
├── launch-screen@1.1.1                       
└── mobile-status-bar@1.0.14                  
mongo@1.2.0                                   
├─┬ allow-deny@1.0.6                          
│ ├── check@1.2.5 (top level)                 
│ ├── ddp@1.3.0 (expanded above)              
│ ├── ecmascript@0.8.2 (top level)            
│ ├── ejson@1.0.14 (top level)                
│ ├── minimongo@1.3.0 (expanded above)        
│ └── underscore@1.0.10                       
├─┬ binary-heap@1.0.10                        
│ ├── id-map@1.0.9 (expanded above)           
│ └── underscore@1.0.10                       
├── callback-hook@1.0.10 (expanded above)     
├── check@1.2.5 (top level)                   
├── ddp@1.3.0 (expanded above)                
├── diff-sequence@1.0.7 (expanded above)      
├── ecmascript@0.8.2 (top level)              
├── ejson@1.0.14 (top level)                  
├── minimongo@1.3.0 (expanded above)          
├─┬ mongo-dev-server@1.0.1                    
│ └── modules@0.10.0 (expanded above)         
├── mongo-id@1.0.6 (expanded above)           
├── npm-mongo@2.2.30                          
├── random@1.0.10 (top level)                 
├── tracker@1.1.3                             
└── underscore@1.0.10                         
nimble:restivus@0.8.11                        
├── accounts-password@1.4.0 (top level)       
├── check@1.2.5 (top level)                   
├── coffeescript@1.12.7_1 (expanded above)    
├─┬ simple:json-routes@2.1.0                  
│ ├── underscore@1.0.10                       
│ └── webapp@1.3.18 (expanded above)          
└── underscore@1.0.10                         
olragon:uri-js@1.13.1                         
pahans:inline-help@1.0.2                      
├── handlebars@1.0.7                          
├─┬ showdown@1.0.8                            
│ └── markdown@1.0.12                         
└── templating@1.3.2 (expanded above)         
peppelg:bootstrap-3-modal@1.0.4               
├── jquery@1.11.10 (top level)                
└── templating@1.3.2 (expanded above)         
percolate:migrations@0.9.8                    
├── check@1.2.5 (top level)                   
├── logging@1.1.17 (top level)                
├── mongo@1.2.0 (top level)                   
└── underscore@1.0.10                         
percolate:synced-cron@1.3.2                   
├── check@1.2.5 (top level)                   
├── logging@1.1.17 (top level)                
├── mongo@1.2.0 (top level)                   
└── underscore@1.0.10                         
pfafman:filesaver@1.3.2                       
raix:handlebar-helpers@0.2.5                  
├── deps@1.0.12 (expanded above)              
├── session@1.1.7 (top level)                 
├── ui@1.0.13 (expanded above)                
└── underscore@1.0.10                         
raix:rssfeed@0.0.5                            
└── webapp@1.3.18 (expanded above)            
raix:ui-dropped-event@0.0.7                   
├── templating@1.3.2 (expanded above)         
└── ui@1.0.13 (expanded above)                
rajit:bootstrap3-datepicker@1.7.1             
└── jquery@1.11.10 (top level)                
random@1.0.10                                 
├── ecmascript@0.8.2 (top level)              
└── underscore@1.0.10                         
reactive-dict@1.1.9                           
├── ecmascript@0.8.2 (top level)              
├── ejson@1.0.14 (top level)                  
├── tracker@1.1.3                             
└── underscore@1.0.10                         
reactive-var@1.0.11                           
└── tracker@1.1.3                             
reload@1.1.11                                 
├── ecmascript-runtime@0.4.1 (expanded above) 
└── underscore@1.0.10                         
reywood:publish-composite@1.5.2               
├── check@1.2.5 (top level)                   
├── ecmascript@0.8.2 (top level)              
├── modules@0.10.0 (expanded above)           
└── underscore@1.0.10                         
sacha:spin@2.3.1                              
├── templating@1.3.2 (expanded above)         
└── underscore@1.0.10                         
service-configuration@1.0.11                  
├── accounts-base@1.3.2 (top level)           
└── mongo@1.2.0 (top level)                   
session@1.1.7                                 
├── ejson@1.0.14 (top level)                  
├── reactive-dict@1.1.9 (top level)           
└── underscore@1.0.10                         
shell-server@0.2.4                            
└── ecmascript@0.8.2 (top level)              
simple:reactive-method@1.0.2                  
├── ddp@1.3.0 (expanded above)                
├── ejson@1.0.14 (top level)                  
└── tracker@1.1.3                             
softwarerero:accounts-t9n@1.3.11              
├── coffeescript@1.12.7_1 (expanded above)    
└── deps@1.0.12 (expanded above)              
spacebars@1.0.15                              
├── blaze@2.3.2 (expanded above)              
├── htmljs@1.0.11 (expanded above)            
├── observe-sequence@1.0.16 (expanded above)  
├── tracker@1.1.3                             
└── underscore@1.0.10                         
spiderable@1.0.14-release-testing.0           
├── callback-hook@1.0.10 (expanded above)     
├── ddp@1.3.0 (expanded above)                
├── templating@1.3.2 (expanded above)         
├── tracker@1.1.3                             
├── underscore@1.0.10                         
└── webapp@1.3.18 (expanded above)            
standard-minifier-css@1.3.4                   
└─┬ minifier-css@1.2.16                       
  └── underscore@1.0.10                       
standard-minifier-js@2.1.1                    
├── babel-compiler@6.20.0 (expanded above)    
├── ecmascript@0.8.2 (top level)              
└─┬ minifier-js@2.1.3                         
  └── babel-compiler@6.20.0 (expanded above)  
tap:i18n@1.8.2                                
├── aldeed:simple-schema@1.5.3 (top level)    
├─┬ cfs:http-methods@0.0.32                   
│ ├── ejson@1.0.14 (top level)                
│ ├── underscore@1.0.10                       
│ └── webapp@1.3.18 (expanded above)          
├── check@1.2.5 (top level)                   
├── coffeescript@1.12.7_1 (expanded above)    
├── jquery@1.11.10 (top level)                
├── meteorspark:util@0.2.0                    
├── raix:eventemitter@0.1.3 (expanded above)  
├── session@1.1.7 (top level)                 
├── templating@1.3.2 (expanded above)         
├── tracker@1.1.3                             
└── underscore@1.0.10                         
tap:i18n-ui@0.8.0                             
├─┬ amplify@1.0.0                             
│ └── jquery@1.11.10 (top level)              
├── coffeescript@1.12.7_1 (expanded above)    
├── tap:i18n@1.8.2 (top level)                
├── templating@1.3.2 (expanded above)         
└── underscore@1.0.10                         
tmeasday:publish-counts@0.8.0                 
├── mongo@1.2.0 (top level)                   
└── underscore@1.0.10                         
todda00:friendly-slugs@0.6.0                  
├── check@1.2.5 (top level)                   
├── coffeescript@1.12.7_1 (expanded above)    
├── matb33:collection-hooks@0.8.4 (top level) 
└── underscore@1.0.10                         
tracker@1.1.3                                 
twbs:bootstrap@3.3.6                          
└── jquery@1.11.10 (top level)                
u2622:persistent-session@0.4.4                
├── amplify@1.0.0 (expanded above)            
├── ejson@1.0.14 (top level)                  
├── jquery@1.11.10 (top level)                
├── reactive-dict@1.1.9 (top level)           
├── session@1.1.7 (top level)                 
├── tracker@1.1.3                             
└── underscore@1.0.10                         
useraccounts:bootstrap@1.14.2                 
├── templating@1.3.2 (expanded above)         
├── underscore@1.0.10                         
└── useraccounts:core@1.14.2 (top level)      
useraccounts:core@1.14.2                      
├── accounts-base@1.3.2 (top level)           
├── blaze@2.3.2 (expanded above)              
├── check@1.2.5 (top level)                   
├── http@1.2.12 (top level)                   
├── jquery@1.11.10 (top level)                
├── reactive-dict@1.1.9 (top level)           
├── reactive-var@1.0.11 (top level)           
├── softwarerero:accounts-t9n@1.3.11 (top level)
├── templating@1.3.2 (expanded above)         
└── underscore@1.0.10                         
useraccounts:flow-routing@1.14.2              
├── check@1.2.5 (top level)                   
├── kadira:flow-router@2.12.1 (top level)     
├── underscore@1.0.10                         
└── useraccounts:core@1.14.2 (top level)      
vsivsi:file-collection@1.3.8                  
├── check@1.2.5 (top level)                   
├── coffeescript@1.12.7_1 (expanded above)    
├── minimongo@1.3.0 (expanded above)          
├── mongo@1.2.0 (top level)                   
└── webapp@1.3.18 (expanded above)            
zimme:active-route@2.3.2                      
├── check@1.2.5 (top level)                   
├── coffeescript@1.12.7_1 (expanded above)    
├── reactive-dict@1.1.9 (top level)           
└── underscore@1.0.10
```

**Comment by anarva** [comment]
Inspection of Atmosphere and NPM packages did not reveal big overlaps or redundant code. There are of course some, but the reward for removing them is not significant at this point.
