### ISSUE TITLE
Remove ShareJS from project dependencies

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2912]
While auditing project dependencies ( #2911 ), it became apparent that [mizzao:ShareJS](https://github.com/mizzao/meteor-sharejs) accounts for around 15% of our project bundle size:

![screenshot_20170914_123611](https://user-images.githubusercontent.com/17307/30422665-4d00bc2a-9949-11e7-8c34-313a9cfae805.png)

# Goal
Reduce our bundle size by removing unneeded dependencies.

# Task
- [ ] Determine why ShareJS is included in our project
    - it may be related to [Ace editor](https://ace.c9.io/)
- [ ] If any component of SharaeJS is used, refactor the code to depend only on the necessary part
- [ ] Install any smaller NPM module that might provide needed functionality
- [ ] Remove the ShareJS package, if possible

**Comment by Vellames** [comment]
@brylie I take a look in the code and a find one use for the ShareJS. In imports page `/apis/import`
I did not continue because i found an error when i tried to import a configuration API file. I will open a issue to fix this problem.

**Comment by brylie** [comment]
I am thinking we need to re-do the API import page, so that it doesn't need ShareJS.

cc: @bajiat

**Comment by bajiat** [comment]
I'm ok with removing the ShareJS package and temporarily disallowing import route, since the page does not work anyway. 

We agreed with @brylie that he would create an issue for user flow of exporting and importing API settings.

**Comment by brylie** [comment]
Related issue: https://github.com/apinf/platform/issues/2945

**Comment by bajiat** [comment]
@Vellames What is the status of this task? Is there a connected PR?

**Comment by bajiat** [comment]
@Vellames Will this task be completed together with #2945?

**Comment by preriasusi** [comment]
@Vellames ping

**Comment by marla-singer** [comment]
@preriasusi Closed this issue because It was resolved in the PR #2973
