### ISSUE TITLE
Create helper function for internationalized text sorting

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2981]
Our codebase has a few places where we want to sort strings in proper internationalized form. For example, when sorting the API Catalog by name, we want to include proper sorting for international characters (such as åäö). To achieve this, we have had to write helper code in the places where internationalized sorting is needed, and this code is duplicated in those places.

# Examples
https://github.com/apinf/platform/blob/2d4105c2ac092cdcb042570d377d1846c50483ba/apinf_packages/api_catalog/client/api_catalog.js#L174-L182

https://github.com/apinf/platform/blob/38bc28a07a974cc0d878d53559acc1ca6cf879a9/apinf_packages/organizations/client/profile/apis/apis.js#L117-L123

https://github.com/apinf/platform/blob/c5302f5eb6ce30f185d40d30d13c9d6459ac39cc/apinf_packages/dashboard/client/view/summary_statistics/summary.js#L63-L69

# Goals
- Re-use a single function for internationalized sorting
- Improve the maintainability of our code by re-using code
- improve readability of code by using abstraction

# Task
- [ ] Determine views in APInf that offer internationalized sorting (e.g. sorting by name)
- [ ] Locate code that performs internationalized sorting
- [ ] Refactor code to be located in common funciton (e.g. in a string_utils.js file)
- [ ] Use the utility function in all places that originally had duplicated sorting code
- [ ] Write a unit test to cover the internationalized sorting utility function

# Ancillary note
MongoDB may, at this point, support proper internationalized sorting. If so, determine if/how we might rely on Mongo/Minimongo directly, rather than maintaining our own utility function.
