### ISSUE TITLE
Monitoring history

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3521]
We have a monitoring feature. You can setup monitoring from settings, and it will show as a green or red dot next to the API name what is the current status of API.

API monitoring history is just as important as the current state. 

## Task:

 - Study how monitoring works
 - Log the monitoring info to database
- Table with last 24 hours information
 - <s>Implement a graph to show the monitoring. (wireframe needed)</s>

## Additionally to be done

- [ ] Create a new tab `Monitoring` under API Profile

![1](https://user-images.githubusercontent.com/7489044/43311752-ed139258-9193-11e8-8467-67574de92ec2.png)

- [ ] Move monitoring from `Settings` tab to `Monitoring` tab

![2](https://user-images.githubusercontent.com/7489044/43311779-020876c4-9194-11e8-92bf-fdc816537d9e.png)

- [ ] Add to `Monitoring` tab a table with last 24 hours information

![3](https://user-images.githubusercontent.com/7489044/43311835-310deca6-9194-11e8-9cfa-272f34c48933.png)

**Comment by 55** [comment]
Here is a table, it should consist of 24 latest messages. We make call every hour, so last 24 hours information. 

![apinf my first api](https://user-images.githubusercontent.com/7489044/42628218-168068b8-85d8-11e8-9afd-52ac6b62a0eb.png)

Find layout, style and related code of table above here:
https://github.com/apinf/platform/tree/apinf/house-cleaning/apinf_packages/monitoring/client
and here:
https://github.com/apinf/platform/tree/apinf/house-cleaning/apinf_packages/apis/client/profile/status

**Comment by 55** [comment]
For the chart, let's have a separate issue as improvement.

**Comment by matleppa** [comment]
@55 @vinaytech 
I think that in history also information of the monitored endpoint will be needed, because it is possible to change it. 
In table it can be either in own column or combined with details.

**Comment by 55** [comment]
@matleppa agree!

**Comment by matleppa** [comment]
@55 @vinaytech 
What about visibility of the monitoring? Previously it has been under tab Settings, which means, that only API owner can handle it and even see it.

In case the monitoring is under own tab, it'll open possibility to make monitoring history public, so some interested application developer can get some idea, what is the service level of API in question.
However, I think that it is only API owner, who can set the monitoring and change monitoring values.

So, the tickbox Enabled API monitoring, the input for Endpoint to Monitor and Save button must be visible only for API owner.

What do you think?

**Comment by matleppa** [comment]
@vinaytech Let's make it at this time such a way, that Monitoring tab is visible only for API Manager and not visible for other users. 
I.e. similar checking of privileges for Monitoring tab using helper currentUserCanManage, as exists for tabs Export, Settings and Proxy.

**Comment by matleppa** [comment]
There is an old erroneous functionality, which I think, that could be corrected here also.
Currently, when monitoring endpoint is given, it is expected to contain the complete path (also server address and API path). 

This is error prone and in addition to that makes it possible to set monitoring even to completely different API.


![image](https://user-images.githubusercontent.com/23265155/43521604-5638debe-959f-11e8-9f41-3c4e129509b6.png)

I think that here giving the server address must not be possible. This should be implemeted same way as when giving API base path when connecting API to proxy.



API host url is shown, but not editable, and user gives the API base path (if not included in API host url) and the actual endpoint.

When monitoring requests are sent, the URL is formed by combining API host url (in settings) with the input part given here.
In monitoring table there will be visible the input part given here.
@55 What do you think?

![image](https://user-images.githubusercontent.com/23265155/43522181-35c90c92-95a1-11e8-98c6-d2fe8a922602.png)

**Comment by matleppa** [comment]
One more thing. 
There has been an old bug, The privileges for MonitoringData table have been missing, thus previously no records has been created there and thus in MonitoringSettings DB the field data (which points to record in MonitoringData DB) has been _false_.

With this PR the privileges have been given, thus correcting the bug.
However, in case monitoring has been set on to some API before this PR, the value _false_ stays in MonitoringSettings, preventing the collection of monitorings.  

So we need a new migration step
  - loop through MonitoringSettings table and if a record with data = _false_ is found, create a record for API in question into MonitoringData and fill the id of created record into field data in MonitoringSettings.

**Comment by matleppa** [comment]
I created a new issue #3535 about giving only endpoint when starting monitoring and displaying also the endpoint in monitoring table.
