### ISSUE TITLE
List users organizations on overview page

### ISSUE THREAD

**Issue by 55** [apinf/platform#3549]
### Description

Show users' organizations on new `Overview` page of NEXT version of Apinf platform.

### User Story

"As an API owner, I need to see organizations I am part of in a simple list. "

### TODO

- [ ] list organizations that user has manager rights
- [ ] limit number of organizations to 6 sort by number of stars
- [ ] show link to catalog filtered by `My organizations` to view all users' organizations
- [ ] include search

**Use this (TBD) mockup and code in this (TBD) branch for layout.**

**Comment by ilarimikkonen** [comment]
icebox- wait until branch  merge is done
