### ISSUE TITLE
Perform functional design review of Dashboard

### ISSUE THREAD

**Issue by brylie** [apinf/platform#470]
Ensure that the primary Dashboard view provides adequate situation awareness for end user. Also ensure users can drill-down to specific details, as needed.
## Task
- [ ]  Identify key user stories relating to dashboard
- [ ] Compare each dashboard element against user goals
- [ ] Ensure that each dashboard element effectively encodes and summarizes relevant information
- [ ] Ensure dashboard elements are integrated and allow for data exploration on request

**Comment by brylie** [comment]
@ccsr has discovered an elegant dashboard interface, with open sourcecode:
https://stats.ethdev.com/
https://github.com/cubedro/eth-netstats

**Comment by bajiat** [comment]
Related to #2024
