### ISSUE TITLE
Clean up unused and remaining collections

### ISSUE THREAD

**Issue by brylie** [apinf/platform#496]
There may be collections that are no longer in use. E.g. `ApiConfigurations`, `RateLimit`. Cleanup unused collections and move remaining collections under a global `Collections` object. Make sure project code still functions, e.g. queries, views, etc.
# Task
## Documentation
- [ ] Make list of all project collections
- [ ] Identify whether each collection is in use
## Cleanup
- [ ] Remove unused collections
## Organize remaining
- [ ] Create global `Collections` object (similar to `Schemas` but for containing collecitons)
- [ ] Move remaining collections under a new, global `Collections` object
## Code cleanup
- [ ] Remove any code fragments relating to unused collections
## Linter configuration
- [ ] Update our .jshintrc to remove unused collection/schema globals
- [ ] Add `Collections` global object 'ignore undefined' rule

**Comment by mauriciovieira** [comment]
Related to #497

**Comment by bajiat** [comment]
Closing during icebox cleanup.
