### ISSUE TITLE
Remove Mailgun as a system dependency

### ISSUE THREAD

**Issue by brylie** [apinf/platform#502]
Mailgun is currently 'hard-wired' to our authentication system. Therefore, it is necessary to set up and activate a Mailgun account to even install Apinf. Lets separate our system from Mailgun.
## Task
- [ ] Create mailgun settings page
- [ ] Add mailgun configuration settings to form on settings page
- [ ] Add corresponding Mailgun Settings schema
- [ ] Create conditional logic to send welcome email via email only when Mailgun settings are available

**Comment by jykae** [comment]
In the production environment I propose using Postfix for SMTP, http://www.hiddentao.com/archives/2014/12/18/meteor-localhost-smtp-using-postfix-on-ubuntu/
It requires more work than Mailgun, so for development I think Mailgun is fine, imho.

**Comment by bajiat** [comment]
Related to #327.

**Comment by bajiat** [comment]
Any SMTP service or server can be used with some configuration. Closing as completed.
