### ISSUE TITLE
Enhance i18n support

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#508]
This task is related to task #481, which consisted of adding basic i18n support for most UI elements. i18n support needs also to be added to autoforms and collections. Furthermore, there  should be an option for selecting UI language, 
# Task
## Research
- [x] Determine where task #481 left off, with regards to adding i18n to UI elements
- [x] Choose i18n packages for remaining UI elements and data
## Implement
- [x] add i18n support to remaining UI elements and data. E.g.
  - [x] Collections
  - [x] Forms
## Review
- [ ] Review whether there are other elements that need to be internationalized, such as date, numbers.
  - [ ] Document any additional work that is required as Github issues.
# Resources
- For autoform, use  [Meteor Autoform i18n](https://github.com/gwendall/meteor-autoform-i18n/)
- For collections, use e.g. [tap:i18n-db](https://github.com/TAPevents/tap-i18n-db). See [demonstration video](https://www.youtube.com/watch?v=cu_dsoIc_0E).
- User interface helpers for language selection, etc. as part of the [tap:i18n-ui package ](https://github.com/TAPevents/tap-i18n-ui)

**Comment by mauriciovieira** [comment]
@bajiat I can take this one.

**Comment by bajiat** [comment]
@mauriciovieira Ok. Thanks for the self-assignment and time estimation!

**Comment by brylie** [comment]
Co-pilot: @brylie

**Comment by bajiat** [comment]
@mauriciovieira Can you please add the estimate for size (remaining hours)? 13?

**Comment by mauriciovieira** [comment]
@bajiat 8

**Comment by bajiat** [comment]
Closing as completed. Even lists are sorted, days are localised for most part, accounts templates solved and pluralization is possible. Any individual improvement needs should be opened as individual issues.
