### ISSUE TITLE
Create document comparing API Umbrella and Kong

### ISSUE THREAD

**Issue by brylie** [apinf/platform#648]
Stakeholders are interested to know the differences between API Umbrella and Kong. Create a comparison document listing similarities and differences between the two projects.
## Definition of done
- [ ] Document should include feature listing of each solution.
- [ ] Document should use consistent terminology for similar functionality.
- [ ] Document should described the underlying technologies.
- [ ] Document indicate when feature is not open source or freely available.
- [ ] Which organizations are behind the two solutions?

**Comment by kyyberi** [comment]
+1

**Comment by kyyberi** [comment]
Size of user community for each? Might be hard to find out

**Comment by kyyberi** [comment]
Commit frequencies or something to show development intensity. That indicates liveliness of development and a small promise of continuity?

**Comment by ahmadnassri** [comment]
happy to contribute info on the Kong side ;)

**Comment by ilarimikkonen** [comment]
we are doing comp analysis anyway
