### ISSUE TITLE
Add self-referencing Swagger file to API Umbrella for Admin API

### ISSUE THREAD

**Issue by brylie** [apinf/platform#920]
We are currently maintaining a Meteor.js integration package for API Umbrella Admin API. When we started the project, the Admin API did not have significant documentation, nor a Swagger description file. The API Umbrella project now has a generic Swagger description file for the Admin API.

As an extension, we would like to use the swagger.js to automatically interface with an API Umbrella instance, so that we can deprecate our Meteor.js package. To this end, we have created an [upstream feature request](https://github.com/NREL/api-umbrella/issues/211), and will begin working to provide this functionality as an upstream contribution.
# Definition of done
- [ ] Create/reuse a repository in apinf organization containing a fork of API Umbrella
- [ ] Add modifications to the fork to meet the following criteria
  - [ ] API Umbrella should have a route to serve a self-referencing swagger.json
  - [ ] That swagger.json should document most or all Admin API endpoints
  - [ ] The swagger.json base URL should be set automatically to the current deployment URL
  - [ ] Optionally, use static documentation or autogenerate swagger.json
# Resources
## API Umbrella
- [API Umbrella feature request related to this task](https://github.com/NREL/api-umbrella/issues/211)
- [API Umbrella Admin API documentation](http://api-umbrella.readthedocs.io/en/latest/admin/api.html)
  - [swagger.yaml](http://api-umbrella.readthedocs.io/en/latest/_static/admin-api-swagger.yml)
- API Umbrella sourcecode: [Admin API V1](https://github.com/NREL/api-umbrella/tree/master/src/api-umbrella/web-app/app/views/api/v1)
## Swagger / OpenAPI Spec
- [Swagger.js](https://github.com/swagger-api/swagger-js)
## Apinf
- [Apinf: Meteor API Umbrella module](https://github.com/apinf/meteor-api-umbrella) - to be deprecated

**Comment by brylie** [comment]
@bajiat this would still be useful for integration purposes. It might mean that we could deprecate our Meteor Swagger package in favor of using a generic [Swagger API integration library](https://github.com/swagger-api/swagger-js).

**Comment by brylie** [comment]
Adding multi-proxy tag, since this is related to the API Umbrella integration.

**Comment by bajiat** [comment]
@shaliko This is a task that would be immediately useful for us and probably requires looking at Api Umbrella source code. Could you look into this? If you wan more details, we can have a meeting or we can use chat to discuss. @brylie would be able to explain in more detail.

**Comment by shaliko** [comment]
@bajiat @brylie OK, will be good have a meeting.
