### ISSUE TITLE
API Monetization

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#951]
# Allow API owners to earn money with their API

All APIs are currently open and free to use. Allow for different monetization strategies. This could be pay per call, pay per month, ...
# User story

As an API owner
I need the option to select a monetization strategy
so that I can earn money with my APIs
# Design

To be defined
# Definition of Done

The task is complete when the following criteria are satisfied:
- [ ] API owner can select a monetization strategy
- [ ] Users of the API get billed (e.g. monthly)
- [ ] Metadata is shown for every API
# More information and discussions online

http://nordicapis.com/top-5-api-monetization-models/
http://www.slideshare.net/jmusser/j-musser-apibizmodels2013
https://www.quora.com/What-are-innovative-ways-to-monetize-your-API
http://monetization.apievangelist.com/

**Comment by bajiat** [comment]
What could be minimum level of features for monetization? 

* Define or select pricing rules?
* Generate usage report?
* Generate invoices?
* Download invoices or send invoices directly to users?
* Payment handling?

I don't think we would be able or willing to go for instance to payment handling.

**Comment by philippeluickx** [comment]
@bajiat Good points. Let's focus on a minimum set of requirements for the 1.0 and then gradually improve over time based on feedback and user requests.
My suggestions
- Let's implement only 1 pricing rule, but develop so that we can add more later. I like the tier-based pricing, which gives a lot of flexibility and also allows the freemium model.
- Dollar as only currency for now will do.
- Usage reports could be included in the dashboard? We can also send copies of the invoices to the owner, so they get the basic data there too.
- Generating invoices we should have, so that means that users need to provide all the necessary data (VAT nr, email, ...) The tricky part is that this will not integrate with any accounting software, as we do not have any meaningful message, but we just have to accept that for now.
- Download and email: Both. You need to be able to log in and download previous invoices. But we also need to send an email. The email could be a link to the invoice though if that is easier.
- No payment handling.

The user identification is whatever we need to generate a correct invoice. In some web apps, there is a verification of the VAT nr (e.g. amazon, ...). Not sure if that is in scope though. Not now I presume, but might be a good idea to ask someone from legal.

**Comment by bajiat** [comment]
This also involves informing the API consumer that you have to pay for the usage (in catalog, in single API view). 

Monetization 2.0: Should the consumer also be kept aware of how much they have consumed? Does this mean dashboard for API key usage with payment information?

**Comment by preriasusi** [comment]
Monetisation plans to be re-written soon. Closing this and starting from scratch.
